### ISSUE TITLE
Not showing code in the source code of the page

### ISSUE THREAD

**Issue by jitendersharma** [digitalDataLayer/magento#1]
Hi,
I installed this extension on the webstore in Magento. But when check on http://digitaldatavalidator.com website it is showing Digital Data Layer not detected.
Regards,
Jitender
9780333026

**Comment by mvitorino** [comment]
Hi,

Can you let me know which website it is so I can have a look?

**Comment by jitendersharma** [comment]
Thanks mvitorino
Please find the link http://webdev.illuminated-mirrors.uk.com/

**Comment by mvitorino** [comment]
Your website requires basic authentication so could be that http://digitaldatavalidator.com is not able to access it (nor can I). If you could share credentials with me via email at miguel@persomi.com I could then have a look. Alternatively, you can open the Chrome Developer Tools and enter "digitalData" in the JavaScript Console. If the variable exists, then it means the extension is configured properly.

**Comment by jitendersharma** [comment]
I have remove the security check from the website you can check it.

**Comment by mvitorino** [comment]
I have looked at the site and the variable is really not there in source as you claimed. You should check under your Magento Admin: "System" -> "Configuration" -> "W3C Digital Data Layer" -> "Configuration" and make sure "Enable Digital Data Layer" is selected to "Yes". After that, Flush your Magento Cache.

**Comment by jitendersharma** [comment]
yes i have done it already and I have Magento Cache disabled on that website

**Comment by mvitorino** [comment]
What is the version of Magento you are running?

**Comment by jitendersharma** [comment]
Magento version ver. 1.7.0.2

**Comment by mvitorino** [comment]
We will have get back to you later. I don't believe our extension has been tested with any version of Magento prior to 1.8.

**Comment by jitendersharma** [comment]
Thanks for your help.
I have another website https://www.lightmirrors.co.uk it has same version ver 1.7.0.2 and it is working fine. You can check there. 
waiting for your response

**Comment by mvitorino** [comment]
I wasn't aware https://www.lightmirrors.co.uk was running 1.7. Indeed it was worked absolutely fine for months there. Let me see from our side what we can do to find what http://webdev.illuminated-mirrors.uk.com/ has in particular that is preventing the DDL from being output.
Will get back to you.

**Comment by mvitorino** [comment]
Hi Jitender,

We have updated the extension with exception logging in a couple of key places to help us determine why the output is not being done on your site. Can you please update to the latest version and then enable logging under System -> Configuration -> Advanced -> Developer -> Logging Settings please. Just browse home, category page and product detail and then provide us with the  exception.log generated. Thank you.

**Comment by jitendersharma** [comment]
Hi Vitorino,
Thanks for your reply. Can you please share with me the new updated extension link. So that, I can download it from there and update my code. Then only we can able to find out the problem. 
Thank you.

**Comment by mvitorino** [comment]
Hi,

Sure, the extension was updated directly on the master branch of this repository. You can download the updated code here: https://github.com/digitalDataLayer/magento/archive/master.zip.
Will be waiting for your feedback on the exception.log.

**Comment by jitendersharma** [comment]
Hi, 
After installing the extension i got following error Parse error: syntax error, unexpected '[' in /var/www/httpdocs/app/code/community/DigitalDataLayer/Model/Page/Observer.php on line 996

**Comment by mvitorino** [comment]
Hi,

We may be getting somewhere now. Can you comment out lines 996 to 1000 on that file?

**Comment by jitendersharma** [comment]
Hi Vitorino,
Thanks for your help. Now, it is working fine.

**Comment by mvitorino** [comment]
Hi Jitender,

Are you now able to see the digitalData variable being output in the page source?

**Comment by jitendersharma** [comment]
Yes dear, Now it is working fine and the digitalData variable being output in the page source. And it is now it is showing on digitaldatavalidator.com. Again thank you so much.

**Comment by mvitorino** [comment]
Great, happy to help.
